Importing Libraries

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Importing Dataset- Table 1

In [7]:
df=pd.read_csv('india_fuel_prices.csv')
df.head()

   Unnamed: 0     diesel      petrol
0    Adilabad  99.84 ₹/L  111.83 ₹/L
1  Agar Malwa  94.89 ₹/L  109.70 ₹/L
2        Agra  89.80 ₹/L   96.63 ₹/L
3  Ahmadnagar  93.03 ₹/L  106.53 ₹/L
4   Ahmedabad  92.17 ₹/L   96.42 ₹/L

Data Analysis

In [8]:
df= df.rename(columns={'Unnamed: 0': 'City'})
df.head()

         City     diesel      petrol
0    Adilabad  99.84 ₹/L  111.83 ₹/L
1  Agar Malwa  94.89 ₹/L  109.70 ₹/L
2        Agra  89.80 ₹/L   96.63 ₹/L
3  Ahmadnagar  93.03 ₹/L  106.53 ₹/L
4   Ahmedabad  92.17 ₹/L   96.42 ₹/L

In [9]:
df.isnull().sum()

City      0
diesel    0
petrol    0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   City    698 non-null    object
 1   diesel  698 non-null    object
 2   petrol  698 non-null    object
dtypes: object(3)
memory usage: 16.5+ KB

In [11]:
df['City'].nunique()

698

In [12]:
#Removing rupees/L sign
df['diesel'] = df['diesel'].str[:-4]
df['petrol'] = df['petrol'].str[:-4]
df.head()

         City diesel  petrol
0    Adilabad  99.84  111.83
1  Agar Malwa  94.89  109.70
2        Agra  89.80   96.63
3  Ahmadnagar  93.03  106.53
4   Ahmedabad  92.17   96.42

In [13]:
df['diesel'] = df['diesel'].astype('float')
df['petrol'] = df['petrol'].astype('float')
df.head()

         City  diesel  petrol
0    Adilabad   99.84  111.83
1  Agar Malwa   94.89  109.70
2        Agra   89.80   96.63
3  Ahmadnagar   93.03  106.53
4   Ahmedabad   92.17   96.42

In [14]:
df

            City  diesel  petrol
0       Adilabad   99.84  111.83
1     Agar Malwa   94.89  109.70
2           Agra   89.80   96.63
3     Ahmadnagar   93.03  106.53
4      Ahmedabad   92.17   96.42
..           ...     ...     ...
693       Yadgir   88.25  102.31
694  Yamunanagar   90.11   97.26
695        Yanam   86.59   96.82
696     Yavatmal   93.80  107.29
697    Zunheboto   89.18  101.32

[698 rows x 3 columns]

Max price

In [15]:
Max_diesel = df.sort_values(by = ['diesel'], ascending=False)
Max_petrol = df.sort_values(by = ['petrol'], ascending=False)
print("City with highest diesel price:", Max_diesel.iloc[0]['City'], "with price:", Max_diesel.iloc[0]['diesel'])
print("City with highest petrol price:", Max_petrol.iloc[0]['City'], "with price:", Max_petrol.iloc[0]['petrol'])

City with highest diesel price: Chittoor with price: 100.3
City with highest petrol price: Ganganagar with price: 113.48